update rclone-sync

diff --git a/bin/rclone-sync b/bin/rclone-sync
--- a/bin/rclone-sync
+++ b/bin/rclone-sync
@@ -1,40 +1,49 @@
 #!/usr/bin/env bash
 
-function preFlightCheck()
-{
-    TOOLS=(rclone date)
-    exit_flag=false
-    for TOOL in ${TOOLS[@]}; do 
-        if [ ! -x "$(command -v $TOOL )" ]; then
-            msg "${TOOL} not found!"
-        fi
-    done
-
-    ${exit_flag} && die "Please install the above prerequisites before running this script"
-}
-
-msg() {
-  echo >&2 -e "${1-}"
-}
-
 function die(){
-    echo "ERROR: $@" 
-    exit
+    echo -e "ERROR: $@" >&2
+    exit -1
 }
 
-# DEFAULT_DIRS=(dev/personal Nextcloud ownCloud Dropbox Pictures Music Documents scratch raspi .fonts .mutt .mozilla/firefox/jayghoshter .screenlayout .ssh .terminfo .local/share/mail .password-store .pass.gpg .my-pwds.gpg .zsh-local)
+function ensure_commands()
+{
+    for ARG in "$@"; do
+        [[ -x $(command -v "$ARG") ]] || die "no such command: $1"
+    done
+}
+
+function ensure_files()
+{
+    for ARG in "$@"; do
+        [[ -f "$ARG" ]] || die "File not found: $ARG"
+    done
+}
+
+ROOT=/home/jayghoshter
+
+ensure_commands rclone date
+ensure_files "${ROOT}/.config/rclone/rclone.conf"
 
 # TODO: add scratch
 SYNC_DIRS=(Data Documents Downloads Media bin dev local/share local/config)
 EXCLUDE_PATTERN="/Literature/**" # Excluded because of obscenely long filenames
 REMOTE_NAME=frostheim-encrypted
 REMOTE_PATH=IBT918
-LOG_DIR=$HOME/local/logs/rclone-sync
+LOG_DIR=$ROOT/local/logs/rclone-sync
 LOG_FILE="${LOG_DIR}/$(date +%Y-%m-%d_%H%M%S).log"
 
 mkdir -p ${LOG_DIR}
 
-cd $HOME
+cd $ROOT || die "Could not cd into $ROOT"
 for DIR in ${SYNC_DIRS[@]}; do
-    rclone sync "${DIR}" "${REMOTE_NAME}:${REMOTE_PATH}/${DIR}" --log-file "${LOG_FILE}" --log-level=DEBUG --progress --transfers 4 --sftp-concurrency 4 --rc --check-first --exclude="${EXCLUDE_PATTERN}"
+    echo "Syncing ${DIR} to ${REMOTE_NAME}:${REMOTE_PATH}/${DIR}"
+    rclone --config="${ROOT}/.config/rclone/rclone.conf" \
+        sync "${DIR}" "${REMOTE_NAME}:${REMOTE_PATH}/${DIR}" \
+        --log-file "${LOG_FILE}" --log-level=DEBUG \
+        --progress \
+        --transfers 4 \
+        --sftp-concurrency 4 \
+        --rc \
+        --check-first \
+        --exclude="${EXCLUDE_PATTERN}"
 done
